services:
  mono-actual-sync:
    image: ghcr.io/sviatcraft/mono-actual-sync:latest
    container_name: mono-actual-sync
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      TZ: "Europe/Kyiv"
    volumes:
      - mono_actual_sync_data:/app/backend/data
    restart: unless-stopped

volumes:
  mono_actual_sync_data: